### ISSUE TITLE
is_mobile_view? is now in_mobile_view?

### ISSUE THREAD

**Issue by jorihardman** [brendanlim/mobile-fu#22]
I recently added mobile-fu to my rails 3 app and couldn't figure out why is_mobile_view? was throwing a method not found error. Eventually, I looked in the source and saw that the name has changed. Can you please update the documentation, or change the name back?

**Comment by benlangfeld** [comment]
Did you install as a gem? The gem is from my fork. I hope at some point @brendanlim will do something about this.

**Comment by jorihardman** [comment]
I did use the gem, and with that change, everything is working fine. If I forked it and fixed it, do you think he'd respond to a pull request?

**Comment by benlangfeld** [comment]
No. I'm recommending people consider my fork to be the active one at this stage. If there's bugs in my fork, I'd appreciate pull requests there.

**Comment by jorihardman** [comment]
I decided to patch this issue and also rewrite the plugin to use Rails 3 best practices. I also pulled in some of the other pull requests for this branch. If you want, you can check it out here: https://github.com/jyro215/mobile_fu-rails3. Any comments on the code would be very helpful :)

**Comment by benlangfeld** [comment]
Ok, so apart from using the railtie to extend ActionController, how is this different? I think it's completely off-base to throw that into a new repo and deny @brendanlim's involvement.

**Comment by jorihardman** [comment]
I apologize, but that was not my intent at all. I just wanted practice making a rails 3 gem, and I wanted to incorporate some of the pull requests. I'd be happy to make it a fork though.

**Comment by jorihardman** [comment]
Ok, I've forked this and made you the primary author in the gemspec. Hope that works better for you.
