### ISSUE TITLE
breaks assets pipeline

### ISSUE THREAD

**Issue by tvdeyen** [brendanlim/mobile-fu#25]
If I add `has_mobile_fu` to my `ApplicationController` the link to the main stylesheet is set to `/stylesheets/application.css` in my `application.html.erb` layout.

If I remove `has_mobile_fu` from my `ApplicationController` it is the default Rails 3.1 `/assets/stylesheets/application.css`

**Comment by tvdeyen** [comment]
Ok, forget it. It was using the mobile-fu gem. And this one depends on rack-mobile-detect. This seems to break it.

**Comment by alvesoaj** [comment]
What was the solution?
